### PR TITLE
Fix metainfo

### PR DESCRIPTION
**Pull request by tzeumer**
It enabled/disabled via config file, so this option should work :)

### CODE REVIEW

**Comment by bibliocoll** [comment]
do we have a situation where this change in conduit.js is actually useful? in the TOC view on index.php, the links to publisher pages for articles can savely open inside the #externalFrame they're already in.
checkout.php currently has no hidden #externalFrame waiting to be revealed, so this will likely fail for links in the "view/print" dialog there.

i will let this sit until you commented, and then likely accept the pull request and add the #external* to checkout.php as an intermediary step

i would like to get rid of checkout.php at some point in the coming month and refactor to a "single page app / full ajax" type of setup in the long run (got one eye on emberjs.com for this, but i'm not sure how many JT installations can make the move from a php backend to node. also haven't asked our local IT staff whether they would let me run a node.js server here, so this idea might end up being stillborn)

**Comment by tzeumer** [comment]
I'm not really happy with the scope and position of the "meta" information, yet. But since it can be turned on/off via config, I think this option should either be removed or something should happen (the links above the toc were gone after my last pull?). 

Removing the option... Yes, on the main page it _is_ too much cluttter. But for me it feels pointless having to go to the toc first to get the other links. But I think they can add value (especially if there were linked data services to easily populate them automatically). 

In a way I understand your point of wanting to get rid of checkout.php. On the other hand I sometimes feel like index.php should be split up more by functional parts - not in way of distinct urls but more like a template with includes of functionally distinct parts. It's pretty hard to understand the first time :)

What would be the advantage of using node.js for JT? I have no real experience with node.js (just tried a few things with the portable version) as I'm not the biggest Javascript fan. But I think you mention the main disadvantage yourself - availiabilty of this service in standard infrastructures. Even though it might be "two clicks" to get it set up and running, we are still talking about a tool for libraries - in my experience many even have trouble to get their own domain/website at all ;)

**Comment by bibliocoll** [comment]
right now, JT is an organically grown bunch of monolithic `display: hidden` html and `reveal()`s on one hand and ajaxy background jobs for data gathering on the other hand, and then the index.php/checkout.php schism on top of that. i agree that it could use some gardening.

moving index.php towards just delivering the entry point / container and then breaking out all the ajaxy parts into separate files could make sense. 
i haven't decided on how i would like to handle this whole reveal type of business, but i agree it is pretty confusing to someone looking at index.php for the first time.

there are probably good frameworks for that kind of stuff, i just don't know any of them well enough.

i mentioned emberjs earlier because i keep gravitating back to that for some reason. maybe because our institute website is based on drupal and there being ways of presenting drupal data behind an ember view layer. i haven't explored this space sufficiently yet, but it seems like a path towards integrating our library services with the rest of the site in a seemless manner even if there are disparate backends involved. also, my love for php is rather limited (likewise for JS, but maybe dealing with one type of bad is better than juggling two?)

**Comment by tzeumer** [comment]
> because our institute website is based on drupal
What is it you specifically want to grab from a CMS to display in JT? The other way - integrating JT into a CMS - should be pretty simple. Basically (yeah I know...) it wouldn't require much more than creating a plugin (or however the CMS calls it) and include the index.php. On the other hand, I have only little experience with other CMS than Wordpress (if you consider it a CMS ;)).

> my love for php is rather limited (likewise for JS, but maybe dealing with one type of bad is better than juggling two?)
Well, I only know PHP and JS in respect to web development. And I'm more a "parttime hacker" than anything near a "real" programmer. So it maybe comes down to "if all you have is a hammer, everything looks like a nail"... As I see it, you just can't take JS out of the equation for a dynamic page anyway. But limiting the backend to JS might create just more nails while not making things easier. Also, anything above LAMP requirements makes an adoption in the library world less likely. I'd only consider it for a game changer that really requires more/better tools. :)

**Comment by krugar** [comment]
when we deal with #26 , we should make sure that metainfo is not generated and then discarded in case metadata display is disabled in the config. either "output and hide" or "neither generate nor output". the current "generate and don't output" case makes no sense.

**Comment by tzeumer** [comment]
Values for meta variables are only set if the option in the config is set to true. In class.ListJournals
  $metaPrint = $metaOnline = $metaGotToc = $metaShelfmark = $metaWebsite = '';
  if ($this->prefs->show_metainfo == true) {
  ....

But you are right, in index.php the check for prefs->show_metainfo comes a little late. Has no impact, but shows my bad style (last year) :D. Ooops.

**Pull request merged**
