### PR TITLE
Pr simple cache

### PR DESCRIPTION
**Pull request by tzeumer**
It really improves loading of long TOCs a lot. But small ones pop up instantly too. Might not be perfect, but doesn't break anything. At least I think so :)

### CODE REVIEW

**Comment by krugar** [comment]
looks like we have 2 caching solutions, what now? yours is more complete and since you implement the cache yourself, doesnt add installation requirements (aside from write permissions to the cache dir). 

i kinda like the small code footprint of the Cache_Lite version (#21), and the library i used seems pretty well-tested.

**Comment by tzeumer** [comment]
Yep, had it lying around for a while, but only recently it felt somewhat good. I triggered the pull request just before I saw your comment with the link to your solution. I've got no problem if the pull is declined, Yet, for now I would stick with my solution, because currently only caching the tocs really makes sense. And the tocs are only replaced if there is a different date (instead of "some" cache lifetime). Nothing else is to be configured or checked - or required. This way it "might" even make sense to generate a cache e.g. for alle new editions automatically...

If there were (or will be) more, I'd be in favor of your solution. But you name the one problem yourself - it has dependencies. And I really like it, if it is as easy (out-of-the-box) to set up on nearly any system as possible (so, I'd really like some simple admin page and possibly an "editor" for the records, so no one has to bother with the config files, too).

**Comment by krugar** [comment]
i've got the PR checked out locally and i'm still in the process of poking all the changes with a pointy stick (rrrrreally slow day), but so far i like what i see. likely going to merge later today.

**Comment by krugar** [comment]
fixes coming from my end in a bit:
- use md5 hash of query string for filename instead of the plaintext query. solves (at least some) problems with malformed query strings
- do not cache the response built in case of remote API error in sys/ajax_toc.php, assuming it may have been caused by a temporary outage
- purging of old cache files

to be considered:
- allow the cache dir to be configured (e.g. /tmp/ might be a solution for hosts not able to run a cron job for cache purging)

**Comment by tzeumer** [comment]
Hey, nice. Totally forgot deleting old versions. I skipped using md5 on purpose because I knew that only a date is sent and it kept the file names readable. But you are right, it's not the best idea :)

Bad responses. Good point!

Cache dir is a good idea. Since the cache directory needs writing permissions and the export directory too, it might be a good idea to create one top folder that needs wrting permission. Maybe something like

data
> cache
> export
> input

By not making the path configurable, the documentation only would have to point out, that directory "data" has to be writable by the webserver. I'm not sure, if a cronjob is needed for purging. The easiest way would be to do something like this, before a new cache file is created "rm toc-issn_*.*" - so it could be kept in the script itself :)

**Comment by krugar** [comment]
> I skipped using md5 on purpose because I knew that only a date is sent and it kept the file names readable.

you know that _you_ only sent a date :wink: possible inlets for user/network input must be sanitized. just adding random junk to the query to reach > 240 bytes will result in harmless filename-too-long errors, and it gets only murkier from there on.

there's still a bunch of those unchecked inlets open, some of which _i_ have added recently without proper checks as well. going over those is on my list however (and now tracked under #32)

**Pull request merged**
