### PR TITLE
Always return date of last issue. Just use 'new'-array to indicate if…

### PR DESCRIPTION
**Pull request by tzeumer**
… it is really new

### CODE REVIEW

**Comment by krugar** [comment]
will do some cleanup on this after merging. i think it makes sense to wrap most of the html building block into an `if ($j['new'])` block

**Comment by tzeumer** [comment]
Why? You only want to show new journals? I like seeing old issues too :)

Just a quickt thought: now the absolute date is set everywhere. Thus it should be easy to sort all entries by this date (I think you suggested a default sort by date already somewhere else).

**Comment by krugar** [comment]
relax, there will be an `else` block ;) i just want to refactor that part since theres multiple `if` or `?:` tests for `$j['new']` and some strings built that then arent used and so on. that can be turned into one test and strings not built if not needed, etc

**Comment by tzeumer** [comment]
Oh, misunderstood it. All good :)

**Comment by krugar** [comment]
tracking the open points under #23 from here on

**Pull request merged**
